#!/usr/bin/env bash

function alert () {

  if [ $? != 0 ]; then
    echo "[ERROR] inotifywaitが終了コード$?で終了しました。エラーメッセージ：$out" 
    exit 1
  fi

  changed_path=$(echo $out | awk '{print $1}')
  operation=$(echo $out | awk '{print $2}')

  zenity --notification --text "システムの重要なファイルの変更が検出されました $out"
  zenity --warning --height 400 --width 500 --title "AlexandriteOS FPWS" --text "システムの重要なファイルの変更が検出されました。\n\n これが意図した操作である場合、この警告は無視して構いません。これが意図しない操作である場合、システムに何らかの悪意がある変更が加えられた可能性が高いので以下のディレクトリを調査することを強く推奨します。\n\n\n 変更されたディレクトリ: $changed_path \n\n 操作： $operation \n\n 出力メッセージ: [$out] \n\n\n この警告が表示されたタイミングがシステムの設定を変更した直後やシステムのアップデートを実行した直後であるのなら、この警告は無視して構いません。"

}

while :
do
   
   out=$(inotifywait -q -r -e MODIFY -e CREATE -e DELETE $HOME/dev/FPWS/test)
   alert &

done